import express, { urlencoded } from "express";
import { _dirname } from "../__dirname.js";
import mainRouter from "./routes/mainRoute.js";
import API_Router from "./routes/FILE_API.js";
import musicPlayerRouter from "./routes/musicPlayerRoute.js";
const app= express();
app.use(urlencoded({extended:true}));
app.use(express.static(_dirname+'/public'));
app.use('/', mainRouter);
app.use('/API', API_Router);
app.use('/play', musicPlayerRouter);
export default app;